arb-dir: lib/l10n
template-arb-file: app_es.arb
output-location-file: app_localization.dart #aqui mensiona donde se va a guardar el texto
synthetic-package: false
nullable-getter: false
output-dir: lib/generated 